apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: kaniko-test-run
spec:
  taskRef:
    name: kaniko-build
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: oc-lab-pvc
  params:
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/sn-labs-pedropissarr/tekton-lab:latest
